apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: bluegreen-test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen-test
  template:
    metadata:
      labels:
        app: bluegreen-test
    spec:
      containers:
      - name: bluegreen-test
        image: nginx
        #image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "150Mi"
            cpu: 20m
  strategy:
    blueGreen:
      activeService: active-service
      autoPromotionEnabled: true
      
---

kind: Service
apiVersion: v1
metadata:
  name: active-service
spec:
  type: LoadBalancer
  selector:
    app: bluegreen-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

