apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: nginx:1.18
        name: mynginx
        ports:
        - containerPort: 80
        lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - >
                  echo version2 > /usr/share/nginx/html/index.html;
  

        

