kind: Service
apiVersion: v1
metadata:
  name: active-service
spec:
  type: LoadBalancer
  selector:
    app: bluegreen-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: preview-service
spec:
  type: LoadBalancer
  selector:
    app: bluegreen-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
