apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: bluegreen-test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen-test
  template:
    metadata:
      labels:
        app: bluegreen-test
    spec:
      containers:
      - name: bluegreen-test
        image: nginx

  strategy:
    blueGreen:
      activeService: active-service
      autoPromotionEnabled: true
