apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-www-autoscaling
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: bluegreen-test
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40

---

apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: bluegreen-test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen-test
  template:
    metadata:
      labels:
        app: bluegreen-test
    spec:
      containers:
      - name: rollouts-demo #이미지를 변경하여 배포
        image: nginx
        #image: argoproj/rollouts-demo:green
        #image: argoproj/rollo
        imagePullPolicy: Always
        ports:
        - containerPort: 80

  strategy:
    blueGreen:
      activeService: active-service
      previewService: preview-service
      autoPromotionEnabled: true
