apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: bluegreen-test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen-test
  template:
    metadata:
      labels:
        app: bluegreen-test
    spec:
      containers:
      - name: mem-test
        image: polinux/stress
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "0.5"
        args:
        - -cpus
        - "1"

  strategy:
    blueGreen:
      activeService: active-service
      autoPromotionEnabled: true
