apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: test-aff
spec:
  replicas: 7
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app:  test-aff
  template:
    metadata:
      labels:
        app: test-aff
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ncloud.com/nks-nodepool
                operator: In
                values:
                - prd-api-pool
      containers:
      - name: web-app
        image: nginx:1.16-alpine
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: active-service
      autoPromotionEnabled: true
