apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: web-server
  namespace: test
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web-store
  replicas: 7
  template:
    metadata:
      labels:
        app: web-store
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ncloud.com/nks-nodepool
                operator: In
                values:
                - prd-api-pool
      containers:
      - name: web-app
        image: nginx:1.16-alpine

  strategy:
    blueGreen:
      activeService: active-service
      autoPromotionEnabled: true
