apiVersion: argoproj.io/v1alpha1   
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: bluegreen-test
spec:
  replicas: 4
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: bluegreen-test
  template:
    metadata:
      labels:
        app: bluegreen-test
    spec:
      containers:
      - name: rollouts-demo #이미지를 변경하여 배포
        #image: argoproj/rollo
        image: argoproj/rollouts-demo:blue 
        #image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      #activeService는 이전의 배포된 Blue 서비스
      activeService: active-service

      #previewService는 새롭게 배포될 Green 서비스
      previewService: preview-service

      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: true
